fix(types): move @types/offscreencanvas to dependencies
The declaration files reference OffscreenCanvas, therefore it should be a dependency instead of a devDependency:

```
node_modules/three-stdlib/exporters/GLTFExporter.d.ts:41:75 - error TS2304: Cannot find name 'OffscreenCanvas'.

41 declare type ImageRepresentation = HTMLImageElement | HTMLCanvasElement | OffscreenCanvas | ImageBitmap;
```